# DEB specific CPack configuration parameters
set(CPACK_GENERATOR "DEB")
set(CPACK_DEB_PACKAGE_COMPONENT ON)
set(CPACK_DEB_COMPONENT_INSTALL ON)
set(CPACK_DEBIAN_PACKAGE_SHLIBDEPS ON)

# The core package needs the postinst and postrm scripts
set(CPACK_DEBIAN_core_PACKAGE_CONTROL_EXTRA "${CMAKE_BINARY_DIR}/postinst;${CMAKE_BINARY_DIR}/postrm")

# Package file names
set(CPACK_DEB_core_PACKAGE_NAME "${PACKAGE_NAME_CORE}")
set(CPACK_DEB_core_PACKAGE_FILE_NAME "${PACKAGE_FILE_NAME_CORE}.deb")
set(CPACK_DEB_experimental_PACKAGE_NAME "${PACKAGE_NAME_EXPERIMENTAL}")
set(CPACK_DEB_experimental_PACKAGE_FILE_NAME "${PACKAGE_FILE_NAME_EXPERIMENTAL}.deb")
set(CPACK_DEB_devel_PACKAGE_NAME "${PACKAGE_NAME_DEVEL}")
set(CPACK_DEB_devel_PACKAGE_FILE_NAME "${PACKAGE_FILE_NAME_DEVEL}.deb")

set(CPACK_DEBIAN_experimental_PACKAGE_DEPENDS "maxscale")

message(STATUS "Generating DEB packages for ${DEB_ARCHITECTURE}")
